CREATE SCHEMA IF NOT EXISTS jeff_test;

CREATE TABLE jeff_test.T_PRODUCTS_TPROD(
	ID INT PRIMARY KEY,
	VERTICAL VARCHAR(50),
	PRODUCT VARCHAR(50),
	PRODUCT_TYPE VARCHAR(50),
	PRICE NUMERIC(6,2),
	MARGIN NUMERIC(6,2)
);

CREATE TABLE jeff_test.T_PRODUCT_SCORES_PERSONA_TPSP(
	ID INT,
	PERSONA VARCHAR(20),
	SCORE INT,
	PRIMARY KEY (ID, PERSONA)
);
